import { Component } from '@angular/core';

@Component({
  selector: 'app-address',
  templateUrl: './address.component.html',
  styleUrls: ['./address.component.css'],
})
export class AddressComponent {
  countries: string[] = [
    'Bangladesh',
    'Barbados',
    'Canada',
    'Chad',
    'Congo',
    'Costa Rica',
    'El Salvador',
    'Eritrea',
    'Greece',
    'Guatemala',
    'Guyana',
    'Honduras',
    'Iran',
    'Kiribati',
    'Kuwait',
    'Macedonia',
    'Malaysia',
    'Malta',
    'Mauritania',
    'Mexico',
    'Philippines',
    'Russia',
    'Saint Lucia',
    'Saudi Arabia',
    'Senegal',
    'South Africa',
    'Thailand',
    'Trinidad And Tobago',
    'Angola',
    'Argentina',
    'Benin',
    'Bosnia and Herzegovina',
    'Colombia',
    'Djibouti',
    'East Timor',
    'Ecuador',
    'Egypt',
    'Fiji Islands',
    'Gabon',
    'Iceland',
    'Iraq',
    'Italy',
    'Kazakhstan',
    'Luxembourg',
    'Portugal',
    'Serbia',
    'Sweden',
    'Taiwan',
    'Azerbaijan',
    'Burkina Faso',
    'Cambodia',
    'Cameroon',
    'Cape Verde',
    'Central African Republic',
    'Cuba',
  ];
}
